# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Frodokem_2026_tx/FrodoKEM/Viprj/project_1/project_1.srcs/sources_1/ip/INSTROM/INSTROM.xci
# IP: The module: 'INSTROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Frodokem_2026_tx/FrodoKEM/Viprj/project_1/project_1.gen/sources_1/ip/INSTROM/INSTROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INSTROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Frodokem_2026_tx/FrodoKEM/Viprj/project_1/project_1.srcs/sources_1/ip/INSTROM/INSTROM.xci
# IP: The module: 'INSTROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Frodokem_2026_tx/FrodoKEM/Viprj/project_1/project_1.gen/sources_1/ip/INSTROM/INSTROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INSTROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
