# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Work_prj/Frodokem_2026_tx/FrodeKEM/SRC/clk.xdc

# IP: ip/ADDRBASE_ROM/ADDRBASE_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADDRBASE_ROM || ORIG_REF_NAME==ADDRBASE_ROM} -quiet] -quiet
